### ISSUE TITLE
Using with AWS Lambda

### ISSUE THREAD

**Issue by TheChedda** [zach-taylor/splunk_handler#29]
Trying to get this to work with Lambda. I read your notes on the matter and implemented them. However, I am pretty sure I messed it up badly as its not working. I made sure to install the splunk handler with pip to my projects directory along with the python script. I then uploaded the .zip and don't see any errors about importing anything so that is all fine. My problem is that when I test, I get a "Task timed out after 3.00 seconds". I am assuming it is my fault as I am not that great with Python yet. Any guidance would be greatly appreciated.

```
from splunk_handler import SplunkHandler
from splunk_handler import force_flush
import logging

def lambda_handler(event, context):
    splunk = SplunkHandler(
        host='<my_splunk_instance>',
        port='8088',
        token='<my_splunk_token>',
        index='test_index'
        #hostname='hostname', # manually set a hostname parameter, defaults to socket.gethostname()
        #source='source', # manually set a source, defaults to the log record.pathname
        #sourcetype='sourcetype', # manually set a sourcetype, defaults to 'text'
        #verify=True, # turn SSL verification on or off, defaults to True
        #timeout=60, # timeout for waiting on a 200 OK from Splunk server, defaults to 60s
        #flush_interval=15.0, # send batch of logs every n sec, defaults to 15.0, set '0' to block thread & send immediately
        #queue_size=5000, # a throttle to prevent resource overconsumption, defaults to 5000
        #debug=False, # turn on debug mode; prints module activity to stdout, defaults to False
        #retry_count=5, # Number of retry attempts on a failed/erroring connection, defaults to 5
        #retry_backoff=2.0,  # Backoff factor, default options will retry for 1 min, defaults to 2.0
    )

    logging.getLogger('').addHandler(splunk)

    logging.warning('hello!')
    force_flush()  # Flush logs in a blocking manner
```

**Comment by syunwei** [comment]
Hi TheChedda,

Have you tried to set verify to False?

Cheers,
Cathy

**Comment by AlonFasta** [comment]
Hi @TheChedda,

This issue happened to me as well,
In my case the issues were:
1. Splunk host - 'my_splunk_instance' should not include http/https scheme or port.
2.my splunk index was wrong, i have set the 'index' to None and it worked

Fasta
