### ISSUE TITLE
Using with AWS Lambda that is triggered by API Gateway

### ISSUE THREAD

**Issue by JonHolman** [zach-taylor/splunk_handler#39]
Most of my lambdas are triggered by API Gateway, so my handlers end with something like:
```
    return {'statusCode': 200,
            'body': json.dumps(data),
            'headers': {'Content-Type': 'application/json'}}
```

Should I put `force_flush()` before the return?  Wouldn't that impact my API performance?

**Comment by AetherDeity** [comment]
@JonHolman , it could have a potential impact if there are outstanding logs waiting to be sent. The alternative is to return and hope all the logs were submitted before the environment is terminated, which occurs once you return. I would recommend just using CloudWatch in lieu of the later.
