### ISSUE TITLE
Can you make index optional..

### ISSUE THREAD

**Issue by projx** [zach-taylor/splunk_handler#41]
Hi

When configuring a HEC in Splunk it requires a default index to be specified, which get used if no "index" if specified in the HEC request. 

Given this, it would be useful to make it optional in Splunk Handler, that way, if a change is needed of the back-end (i.e. migrating to different index), it avoids the next to also update the code.

**Comment by jeffreymelvin-wf** [comment]
Would this not be equivalent to setting it to an empty string or None in the code that instantiates the handler?
