### ISSUE TITLE
Error cannot import name 'SplunkHandler' from 'splunk_handler' (unknown location)

### ISSUE THREAD

**Issue by redcorjo** [zach-taylor/splunk_handler#56]
Hi,

I am trying to use the splunk handler at my python 3.7 lambda but when calling the import the code fails with error "Error cannot import name 'SplunkHandler' from 'splunk_handler' (unknown location)". At the root folder fo my lamda I imported all dependencies with "pip3.7 install requests splunk_handler -t ."

Anyone else suceeded to get it running?

**Comment by JeffreyLMelvin** [comment]
Please see the usage documentation in this repo's Readme

**Comment by redcorjo** [comment]
Apologies to insist, but I already took a look to the documentation prior of creating the issue. I am already using the force_flush section from documented instructions.

try:
    from splunk_handler import force_flush
    print("Using splunk handler")
    use_force_flush = True
except:
    use_force_flush = False
#from modules import stream_handler


If it is something else when you referred about given docmentation I will really appreciate your guidance. Many thanks!

**Comment by JeffreyLMelvin** [comment]
If it isnt importing, you havent installed it correctly. Double check your lambda package to verify you are deploying the package and it is in the correct location.
